### ISSUE TITLE
Lava tree

### ISSUE THREAD

**Issue by ghost** [galang8664/local_manifest#1]
Don't use lava tree from this sorce

**Comment by langw4y** [comment]
> 



> Don't use lava tree from this sorce

why?

**Comment by ghost** [comment]
It get clang error

**Comment by ghost** [comment]
https://github.com/PixelExperience-Devices/device_xiaomi_lava


Use it

**Comment by langw4y** [comment]
> https://github.com/PixelExperience-Devices/device_xiaomi_lava
> 
> Use it

ok i will try it

**Comment by ghost** [comment]
https://github.com/Arafattex/local_manifest/tree/Lancelot_pixel



Here my local manifest should help you

I am @shas45558 it tg

What is your tg name
